name: openai_chatbot
channels:
  - conda-forge
  - https://conda.anaconda.org/erik
  - defaults
dependencies:
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - anyio=4.0.0
  - appdirs=1.4.4
  - async-timeout=4.0.2
  - attrs=22.2.0
  - boto3=1.28.44
  - botocore=1.31.44
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - contourpy=1.0.7
  - cryptography=40.0.1
  - cycler=0.11.0
  - docker-pycreds=0.4.0
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.3
  - flask=2.2.3
  - fonttools=4.39.3
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gitdb=4.0.10
  - gitpython=3.1.31
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=0.17.3
  - httpx=0.24.1
  - hyperframe=6.0.1
  - idna=3.4
  - importlib-metadata=6.3.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - kiwisolver=1.4.4
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=16.0.1
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libtiff=4.5.0
  - libwebp-base=1.3.0
  - libzlib=1.2.13
  - llvm-openmp=16.0.1
  - markupsafe=2.1.2
  - matplotlib-base=3.7.1
  - multidict=6.0.4
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.24.2
  - openai=0.27.2
  - openjpeg=2.5.0
  - openpyxl=3.1.1
  - openssl=3.1.2
  - packaging=23.0
  - pandas=2.0.0
  - pathtools=0.1.2
  - pillow=9.5.0
  - pip=23.0.1
  - platformdirs=3.2.0
  - plotly=5.14.1
  - pooch=1.7.0
  - protobuf=4.21.12
  - psutil=5.9.4
  - pycparser=2.21
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-telegram-bot=20.4
  - python-tzdata=2023.3
  - pytz=2023.3
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.2
  - s3transfer=0.6.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - sentry-sdk=1.19.1
  - setproctitle=1.3.2
  - setuptools=67.6.1
  - six=1.16.0
  - slack-sdk=3.21.0
  - smmap=3.0.5
  - sniffio=1.3.0
  - tenacity=8.2.2
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tqdm=4.65.0
  - types-pytz=2023.3.0.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wandb=0.14.2
  - werkzeug=2.2.3
  - wheel=0.40.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zipp=3.15.0
  - zstd=1.5.2
  - pip:
    - slack-bolt==1.17.0
